# Generated by Django 2.2.20 on 2021-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_make_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='make_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
